# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0002_auto_20160308_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageitem',
            name='created',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messageitem',
            name='updated',
            field=models.TextField(),
        ),
    ]
